print("\n########n##########################")
print("#                                 #")
print("#       MUHAMMAD NAFIS PUTRA      #")
print("#          2410817210021          #")
print("#                                 #")
print("########n##########################")